##################
# rebinding keys #
##################

# prefix
unbind C-b
set -g prefix C-Space 
bind C-Space send-prefix


# creating splits
bind | split-window -h -c "#{pane_current_path}"

# mouse
set -g mouse on

# QOL features
set -g base-index 1
set -g renumber-windows on
set -s default-terminal 'tmux-256color'

#######
# VIM #
#######

# vim copy and view mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

bind v copy-mode

# vim pane navigation
bind h select-pane -L
bind j select-pane -D
bind l select-pane -R
bind k select-pane -U

# vim resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r L resize-pane -R 5
bind -r K resize-pane -U 5

#########
# Style #
#########
set -g status-interval 1
set -g status-position bottom
set -g status-justify left

set -g pane-active-border-style fg="#935362"
set -g pane-border-style fg="#42252B"

set -g status-style bg="#935362",fg="#FFFFFF"
set -g status-right ""
set -g status-left "#[fg=#FFFFFF][#S] "

set -g window-status-format " #I:#W "
set -g window-style default
set -g window-active-style default
set -g window-status-style default

