enable_audio_bell no
font_family	Iosevka
bold_font auto
italic_font auto
bold_italic_font auto
font_size 16.0



background_opacity 0.6
background_blur 1

#black
color0 #000000
color8 #767676

#red
color1 #9e4238
color9 #cc5446

#green
color2  #449a78
color10 #58dca8

#yellow
color3  #bea25b
color11 #fae09b

#blue
color4  #935361
color12 #7ebfea

#magenta
color5  #8941AD
color13 #ae4bdf

#cyan
color6  #CE6F85
color14 #58eef0

#white
color7  #dddddd
color15 #ffffff

